---
title: Supplementary Material (A) - Procedure for testing and adjusting translations of the Soundscape (quasi-)Circumplex Model
description: |
  Accompanying the paper: "Soundscape descriptors in eighteen languages: translation and validation through listening experiments
type: manuscript
author:
  - name: Andrew Mitchell
    email: andrew.mitchell.18@ucl.ac.uk
    affiliations: 
        - id: ucl-iede
          name: University College London
          department: Institute for Environmental Design and Engineering
          address: Central House, 14 Upper Woburn Place
          city: London
          state: UK
          postal-code: WC1H 0NN
    attributes:
        corresponding: true
    orcid: 0000-0003-0978-5046
  - name: Francesco Aletta
    email: f.aletta@ucl.ac.uk
    orcid: 0000-0003-0351-3189
    affiliations:
        - ref: ucl-iede
abstract: |
  In depth description for the procedure developed for the paper: "Soundscape descriptors in eighteen languages: translation and validation through listening experiments". The R and Python code for the various tables, figures, and analyses presented in this document can be found in the repository hosted on OSF [https://osf.io/jvna2/](https://osf.io/jvna2/).

format:
  # html:
  #   toc: true
  #   toc-expand: 2
  #   theme: flatly
  #   number-sections: true
  #   code-fold: show
  #   page-layout: full
  #   embed-resources: true
  elsevier-pdf:
    hyperrefoptions: 
      - "citecolor=black"
    echo: false
    latex-clean: true
    keep-tex: true
    toc: false
    journal:
      formatting: preprint
      model: 3p
      cite-style: authoryear
    notebook-links: true

bibliography: FellowshipRefs.bib
date: last-modified
---

# Introduction

In this analysis, we aim to test the circumplex structure of various soundscape survey translations. The circumplex model is a powerful tool in psychology, often used to visualize and interpret complex multivariate data. In order to enable its use across many contexts, cultures, and languages, its necessary to validate the structure of the circumplex items. The goal of validated translations is to ensure that the circumplex structure is maintained across translations, allowing for cross-cultural comparisons.

## Defining the circumplex model

The concept of the psychometric circumplex model, first introduced by @Guttman1954new, revolves around the idea of a circular relationship among variables. This circular relationship can be seen by identifying certain correlation patterns within the correlation matrix among variables, when appropriately ordered [@Browne1992Circumplex]. In the case of the circular structure, the strength of the correlation coefficients in the matrix decreases as you move away from the diagonal, and then increases again as you move towards the opposite diagonal. This pattern of correlations can be seen in @tbl-circumplex.

+------+----------+----------+----------+----------+----------+----------+----------+------+
|      | V1       | V2       | V3       | V4       | V5       | V6       | V7       | V8   |
+======+==========+==========+==========+==========+==========+==========+==========+======+
| V1   | 1        |          |          |          |          |          |          |      |
+------+----------+----------+----------+----------+----------+----------+----------+------+
| V2   | $\rho_1$ | 1        |          |          |          |          |          |      |
+------+----------+----------+----------+----------+----------+----------+----------+------+
| V3   | $\rho_2$ | $\rho_1$ | 1        |          |          |          |          |      |
+------+----------+----------+----------+----------+----------+----------+----------+------+
| V4   | $\rho_3$ | $\rho_2$ | $\rho_1$ | 1        |          |          |          |      |
+------+----------+----------+----------+----------+----------+----------+----------+------+
| V5   | $\rho_4$ | $\rho_3$ | $\rho_2$ | $\rho_1$ | 1        |          |          |      |
+------+----------+----------+----------+----------+----------+----------+----------+------+
| V6   | $\rho_3$ | $\rho_4$ | $\rho_3$ | $\rho_2$ | $\rho_1$ | 1        |          |      |
+------+----------+----------+----------+----------+----------+----------+----------+------+
| V7   | $\rho_2$ | $\rho_3$ | $\rho_4$ | $\rho_3$ | $\rho_2$ | $\rho_1$ | 1        |      |
+------+----------+----------+----------+----------+----------+----------+----------+------+
| V8   | $\rho_1$ | $\rho_2$ | $\rho_3$ | $\rho_4$ | $\rho_3$ | $\rho_2$ | $\rho_1$ | 1    |
+------+----------+----------+----------+----------+----------+----------+----------+------+

: Theoretical pattern of the correlation matrix corresponding to a circular structure. $\rho_1 > \rho_2 > \rho_3 > \rho_4$ [@Gurtman2000Interpersonal]. {#tbl-circumplex .column-page}

This pattern of the corrrelation matrix indicates that the variables are ordered in a circular fashion, with the strongest correlations between adjacent variables, and the weakest correlations between variables that are furthest apart. It also means that the correlations between these variables follow a pattern that increases and decreases in a way that resembles a cosine wave, as explained by @Yik2004Relationship and @Grassi2010CircE. This circular arrangement of the variables can be tested using a method proposed by @Rounds2000Tinsley.

Browne further expanded on the circumplex model in 1992 and 1995 by differentiating between equal spacing and equal communality (or radii) constraints. Browne described four variations of circumplex models, which include three types of quasi-circumplex models and one circulant model. These variations include the unconstrained or loosely ordered quasi-circumplex, the equal spacing quasi-circumplex, the equal communality quasi-circumplex, and the circulant model that maintains both equal spacing and equal communality.

In certain instances, the rigidity of a circumplex may be relaxed, leading to the concept of a quasi-circumplex. The term "quasi" implies a departure from strict adherence to even spacing and equal communality, allowing for some flexibility in the arrangement of variables. This flexibility is often necessary in order to accommodate the complexity of psychological constructs, which may not always fit neatly into a rigid circular structure. It refers to any graphical or conceptual representation where variables or dimensions are organized in a circular or circular-like manner. This umbrella term recognizes the spectrum of circular models, acknowledging variations in the spacing, organization, and relationships among variables.

As researchers delve into the intricacies of psychological spaces, the choice between a strict circumplex, a quasi-circumplex, or a more general circular structure becomes crucial. These models play a pivotal role in visualizing and understanding the complex interplay of variables, offering researchers nuanced frameworks to explore and interpret their data.

@Rogoza2021three (Fig. 1) provides a helpful visualisation of these circumplex variations:

![Graphical representation of four variations of circumplex model structure. Model 1 is a circular model, Model 2 is a quasi-circumplex model with equal spacing, Model 3 is a quasi-circumplex model with equal communality, and Model 4 is a circumplex model with equal spacing and equal communality.^[Reproduced from [@Rogoza2021three] with permission by the publisher.]](Rogoza2021three-fig1.jpg){width=100%}

## Translating circumplex instruments

Typically, circumplex scales are measured via a series of questions in a survey instrument. These instruments are initially developed in one language and the validity and structure of the instrument is tested in that language. Often these instruments are directly translated into other languages to enable their use in other countries. However, the validity of the instrument in the new language is not guaranteed. Changes in the correlation structure can be caused by errors in the translation process, by semantic and linguistic differences between the translated scales even given a valid translation, and by a lack of generalisability of the circumplex instrument.

It is easy to see how errors in the translation process can lead to changes in the correlation structure. For example, if a question is mistranslated, then the responses to that question will not be correlated with the responses to the other questions in the instrument. Semantic and linguistic differences between the translated scales can also lead to changes in the correlation structure. For example, if a question is translated into a language where the concept does not exist or cannot be easily expressed, then the responses to that question will not be correlated with the responses to the other questions in the instrument. Finally, it may be that even if the original instrument is valid for e.g. the English-speaking population, it may not be valid for other populations due to cultural differences.

<!-- ### Goals of translating a circumplex instrument

Two approaches could be taken when attempting to translate a survey instrument. The first approach would attempt to achieve direct concurrence with the original instrument, where each scale is directly correlated with the corresponding scale from the original instrument. If the circumplex structure is identical between the two languages, then this approach would allow for the most direct comparison between the two languages. However, if the circumplex structure is not identical between the two languages, then this approach would lead to a loss of information. The second approach would attempt to achieve the same circumplex structure in the new language as in the original language. This approach would allow for the most direct comparison between the two languages.

In this second approach, identifying the differences in structure between translations enable the process of locating an external variable to be corrected for the differences in structure. Given that at minimum a quasi-circumplex structure can be confirmed, then the deviations in either the angles or communalities from the ideal circumplex structure can be measured and accounted for. When this is done separately for the origianl and translated instruments, then an external variable which has the same theoretical location in both instruments should be located in the same location in both corrected instruments.

This has an important impact on comparing results under the two translations. If an external variable is theoretically located in a single, fixed position in the circumplex space, locating it without accounting for the differences in structure between the two translations will lead to different locations in the two translations. The interpretation of this result would then be that the external variable is located in different positions in the two languages. However, if the differences in structure are accounted for, then the external variable should be located in the same position in both translations. By applying the correction we can attempt to discover differences in the effect of external variables, independent of the differences in structure between the two translations. -->

<!-- ## A test case: The Soundscape Circumplex Model (SCM)

In 2010, @Axelsson2010principal proposed a *principle components* model of soundscape perception. Due to its similarity to the widely-studied Russell's circumplex model of affect [@Russell1980circumplex], Axelsson's principal component model is often referred to as the Soundscape Circumplex Model (SCM) in soundscape literature. The SCM and the Swedish Soundscape Quality Protocol (SSQP) [@Axelsson2012Swedish] utilizing it quickly became the predominant method of soundscape assessment in both scientific literature and professional practice [@Aletta2023Adoption], due to its ease of use, interpretability, and, crucially, its ability to summarise the complex interrelationships between soundscape descriptors within a straightforward and familiar two-dimensional space. Togeter with a similar principal component model in @Cain2013development, the framework of the circumplex model of soundscape perception was subsequently adapted into an integral part of the standardised protocols for soundscape data collection, specifically in Method A of @ISO12913Part2.

Currently, the soundscape community relies very heavily on the framework proposed in @ISO12913Part2, both for theory development and for procuring empirical evidence of the benefits of the soundscape approach, in real life scenarios. In a recent systematic literature review, @Aletta2023Adoption idenitified 254 scientific publications which have referred to ISO 12913 since its publication in 2018, with 50 of them appropriately making use of the data collection methods. Of those, several papers included multiple studies, with 51 studies making use of the SCM as recommended in the ISO standard. In addition, the SCM has been used in many more studies without reference to the ISO standard [@Engel2018Review], and has been haphazardly translated into many languages [@Tarlao2016Comparing; @Nagahata2019Examination; @Tarlao2020Investigating; @Aletta2019Exploringa].

The Soundscape Circumplex Model (SCM) was developed in 2010 by @Axelsson2010principal to describe the perception of ambient sound environments. It has since been used in a number of studies to describe the perception of soundscapes in different contexts and cultures [@ISO12913Part2]. The SCM is composed of eight scales, which closely resemble the eight scales of the Circumplex Model of Affect [@Russell1980circumplex]. The 7 scales are arranged in two bipolar dimensions, with pleasant-annoying along the x-axis (valence) and eventful-uneventful along the y-axis (arousal). Arranged in a circular pattern around the circumplex, beginning at 0 degrees and moving counter-clockwise, the eight scales are: pleasant (0) -->

# A four step procedure for the analysis of circumplex models

This section of the Supplementary Material is intended as an extended companion to Section 3. Data Analysis of the main manuscript. Some text is repeated here, but additional rationales and details are included which were ommitted from the manuscript for conciseness.

In @Rogoza2021three, the authors propose a three-step procedure for assessing circumplex models. The steps in this procedure are: 1) "verify whether the analzed model is circumplex or not" using Structural Equation Modelling based on @Browne1992Circumplex's model; 2) "test the possibility to locate an external variable within empirical circumplex" using the Structural Summary Method [@Gurtman1994differentiating]; and 3) "assess the extent of which empirical locations are in congruence to the theoretical predictions within the circumplex structure" [@Rogoza2021three].

We expand upon the three-step procedure proposed by @Rogoza2021three and adapt it to the specific case of testing multiple variations (i.e. translations) of the same circumplex instrument. The goals of this procedure are, for each translation, to verify the quasi-circumplex structure of the instrument, to derive angle corrections, and to test the congruence between the corrected circumplex and the theoretical circumplex structure. We do this by first adding an initial step to incorporate @Rounds2000Tinsley's test of the circular ordering of the scales to confirm that the order of the scales is maintained across translations. We then follow the same three steps as @Rogoza2021three, but we adapt the third step to test the congruence between the circumplex structure of the original instrument and the circumplex structure of the translated instruments and to allow for adjustments to be made by extracting adjusted angles from the SEM step.

## Step 1: Confirm the circular ordering of the circumplex scales

In line with the procedure taken in @Gurtman2000Interpersonal and previously employed for the SCM by @Lam2022Assessing, we begin by confirming the circular ordering of the circumplex scales. This test, developed by @Rounds2000Tinsley, the test of the circular order model involves comparing the obtained order relations for a set of scales against their hypothesized order given a certain circular model. This test is applied in order to ensure that the process of translation has not altered the order of the scales and so the test is applied against the order of the scales in the original instrument. The test is applied to each translation separately, and the results are compiled into a single table.

The index used for this test is @Hubert1987Evaluating's correspondence index (CI). This offers a descriptive measure reflecting the degree to which the model's ordered predictions align with a specific sample matrix. The metric is calculated as the proportion of predictions met minus the proportion violated, yielding a range from 1.0 (indicating complete prediction fulfillment) to -1.0 (indicating all predictions contradicted). In alignment with the methodology outlined by @Tracey1997RANDALL, we applied a randomization test to the hypothesized order relations [@Hubert1987Evaluating], producing an exact probability, determining the likelihood of achieving the observed model fit in relation to all potential permutations of the matrix. The index thresholds for this test are: a p-value \< 0.05 and a CI \> 0.70.

## Step 2: Confirm the quasi-circumplex structure of the circumplex scales

We confirm the structure of the circumplex instrument by applying @Browne1992Circumplex's circular stochastic process model with a Fourier series correlation function. This model represents a non-standard Structural Equation Model (SEM) specifically tailored to testing circumplex structures which allows a researcher to examine the extent to which the underlying structure of a sample correlation matrix conforms to a circumplex pattern. The four model variations (unconstrained circular, equal spacing quasi-circumplex, equal-communality quasi-circumplex, and strict circumplex with equal spacing and communality) can each be investigated using this model. For the unconstrained and quasi-circumplex models, Browne's model allows for the estimation of the angles and communalities of the circumplex scales. From these results for the quasi-circumplex models, we can derive the corrected angles for each translation, which can be used in the next step of the analysis.

This model is implemented in the CircE package [@Grassi2010CircE] for R [@RCT2018R]^[The version of CircE originally developed by Grassi is no longer maintained and fails on installation in R. As such, the specific version of CircE with bug fixes implemented by the authors used for this analysis is hosted separately on Github at: [https://github.com/MitchellAcoustics/CircE-R](https://github.com/MitchellAcoustics/CircE-R)]. The model is applied to each translation separately, testing each of the four model variations, and the results are compiled into a single table. CircE provides a suite suite of SEM fit indices, which are statistical measures used to evaluate the goodness of fit of the models. For this study, we use the following fit indices: Comparative Fit Index (CFI), Goodness of Fit Index (GFI), and Standardized Root Mean Square Residual (SRMR), summarised with their respective thresholds in @tbl-indices. 

Readers might note that these indices differ slightly from those used by @Rogoza2021three, most notably the exclusion of the Root Mean Square Error of Approximation (RMSEA), a commonly used metric. RMSEA was excluded from the analysis on the basis of both Rogoza's own critiques^["it is worth noting that the RMSEA may not be best suited to evaluate circumplex models. It becomes biased in the case of high correlations between proximal variables, as found in circumplex models, and should be interpreted with caution." [@Rogoza2021three]] and recent warnings from @West2022Handbook.

+-----------------------------------------------+----------------+---------------------------+
| **Fit Index**                                 | **Threshold**  | **Reference**             |
+===============================================+:==============:+:=========================:+
| Correspondence Index (CI)                     | p \< 0.05,     | @Gurtman2000Interpersonal |
|                                               |                |                           |
|                                               | CI \> 0.70     |                           |
+-----------------------------------------------+----------------+---------------------------+
| Comparative Fit Index (CFI)                   | *0.92*         | @Moshona2023Optimization  |
+-----------------------------------------------+----------------+---------------------------+
| Goodness of Fit Index (GFI)                   | *0.90*         | @Rogoza2021three          |
+-----------------------------------------------+----------------+---------------------------+
| Standardized Root Mean Square Residual (SRMR) | *0.08*         | @Hu1999Cutoff             |
|                                               |                |                           |
|                                               |                | @Moshona2023Optimization  |
|                                               |                |                           |
|                                               |                | @Tarlao2020Investigating  |
+-----------------------------------------------+----------------+---------------------------+

: Fit indices and thresholds, including the reference from which the threshold is derived. {#tbl-indices}

Once each of the model variations are assessed against the above fit indices, we can determine whether that model variation is a good fit for the data. If the strict circumplex model meets the fit thresholds across the translations tested, then the procedure can be continued and no adjustment will be needed. If, however, the structure of some or all of the translations are found to have a quasi-circumplex structure, then adjustments will need to be derived and applied to ensure cross-comparability between the translated instruments. If the model variation for the equal-communality model (where the angles are allowed to vary) is a good fit for the data, then we can use the derived angles from CircE as adjustments to the circumplex structure.

<!-- 1.  Comparative Fit Index (CFI): This index compares the model of interest to a baseline model. Values close to 1 indicate a good fit.

1.  Goodness of Fit Index (GFI): This index measures the proportion of variance that is accounted for by the estimated population covariance. Values close to 1 indicate a good fit.

2.  Standardized Root Mean Square Residual (SRMR): This is the square root of the discrepancy between the residuals of the sample covariance matrix and the hypothesized covariance model. Values less than 0.08 are generally considered good.

3.  Procrustes Rotation Congruence (PRC): This index measures the congruence between the ideal and observed angles. Values close to 1 indicate a good fit. -->

Importantly, this table also reports the derived angles for each scale for the unconstrained and Equal comm. models. These angles will be carried over and used in the next stage of the analysis, where we will validate the survey instrument by correlating the survey responses with the acoustic indices using the Structural Summary Method (SSM).

## Step 3: Locate the full dataset circumplex scales within each language's circumplex space

Once the general circumplex structure is tested, it is possible to investigate the likelihood to locate an external variable (this could be an objective feature such as sound level dB or it could be another perceptual or psychometric variable such as tranquility) within the empirical circumplex. The circumplex model provides a precise framework for predicting the relationships between an external variable and all circumplex variables. The Structural Summary Method (SSM) is a technique used to summarize correlation patterns among measurement scores that are hypothesized to conform to a circumplex structure [@Rogoza2021three]. SSM aims to fit a sinusoidal curve to data points ($q_i$) based on their nominal angular positions ($\theta_i$). This is achieved by optimizing the parameters for elevation ($e$), amplitude ($i$), and displacement ($d$). Mathematically, these parameters are used to model the correlational information ($q_i$) in @eq-ssm:

$$
q_i = e + \alpha cos(\theta_i - d)
$$ {#eq-ssm}

SSM analysis yields several key estimations, including:

-   Model fit (R2), which assesses how well the observed sinusoidal curve aligns with the cosine function, indicating the goodness of fit.
-   Elevation, representing the average correlation between an external variable and all circumplex variables.
-   Amplitude (vector length), measuring the distance from the mean of the external variable's correlation to its peak correlation with circumplex variables. This value signifies the uniqueness of the profile, indicating whether it is prominently associated with a specific circumplex variable or equally related to all.
-   Angular displacement, denoting the angle at which the profile reaches its maximum point, indicating the empirical location of the variable within the circumplex as observed in the data.

> It is essential to evaluate how well the sinusoidal curve aligns with the cosine function by examining its goodness of fit, as indicated by the $R^2$ value. If $R^2$ values fall below 0.70, it is advisable not to interpret the remaining coefficients and to discontinue the process of locating external variables. Conversely, $R^2$ values exceeding 0.80 indicate a strong fit. Additionally, it’s worth mentioning that amplitude estimates, reflecting the distinctiveness of the profile, and elevation estimates, indicating the presence of a general factor, are considered notable when they surpass 0.15.

As described in @Rogoza2021three, Step Two involves testing whether external variables can be located within the circumplex.  Because we have derived new angles in the SEM step, we use these 'adjusted' angles for calculating the SSM parameters. In order to determine whether the language circumplexes can adequately allow an external variable to be located, we use the following criteria:

-   $R^2$ \> 0.8
-   amplitude \> .15

These indices are based on the criteria used by @Rogoza2021three, however we use an increased criterion of $R^2 > 0.9$ since we have a prior expectation that the circumplex variables should fit very well within each translation's circumplex.

The structure of the circumplex is key to determining where external variables are located. Given differing angles and communalities, the external variable can occupy different locations within the circumplex. Revealing and validating the true structure of a particular circumplex model is therefore key to reliably identifying correct location of external variables within the circumplex space.

## Step 4: Accurately locating circumplex items within each language

The final step of @Rogoza2021three's three step procedure is to test the congruence between the empirical locations and theoretical expectations within the circumplex structure. In the case of the soundscape circumplex and our SATP data, we don't have an external variable with a defined theoretical location within the circumplex - for instance loudness does not have a defined location within the circumplex where it is expected to be located.

Taking inspiration from @Yik2004Relationship, we propose to use the circumplex structure of the soundscape survey itself as the theoretical expectation. @Yik2004Relationship proposes that one circumplex can be located within another by calculating the SSM correlation between each of the scales of the reference circumplex and the test circumplex. In this way, each scale of the reference circumplex can be located within the test circumplex, and we can test whether these empirical locations meet our expectations.

The process to do this is as follows:

1.  For both the reference and test circumplex, calculate the mean value of each scale for each recording.
2.  Calculate the SSM correlation between each scale of the reference circumplex and the test circumplex, in our case using the corrected angles.
3.  Test the congruence betwen the empirical locations and theoretical expectations using the Procrustes congruence test [@Rogoza2021three].

We will be using the full dataset as the reference set and the data from each translation as the test set. This effectively means that we are testing whether each translation is able to locate the circumplex structure of the soundscape survey, consistently across all languages.

This aligns with the overall goal of our process of allowing data (i.e. the circumplex coordinate) from different languages to be directly compared, by correcting for the differences in the circumplex structure between languages.

### Congruence

What @Rogoza2021three (and Orthosim) refer to as Tucker's Congruence Coefficient is also commonly referred to as the cosine similarity (see the [Tensorly documentation](https://tensorly.org/stable/modules/generated/tensorly.metrics.factors.congruence_coefficient.html)). We therefore use the sklearn implementation of cosine similarity to calculate the congruence between the empirical locations and theoretical expectations. This produces a matrix of cosine similarity values, which we then use to calculate the mean congruence, to match the model congruence from @Rogoza2021three.

### Procrustes

However, it appears that, despite @Rogoza2021three 's description, this method is not actually based on a Procrustes analysis. The equivalent distance metric from a Procrustes method would be the rotational-based Procrustes distance, i.e. the squared Froebenius norm of the difference between the two orthogonal matrices. See @Andreella2023Procrustes:

> Instead, the second distance exploits the orthogonal matrix parameters solution of the Procrustes problem. The rotational-based distance computes the squared Frobenius distance between these estimated orthogonal matrices. As we will see, this metric measures the level of dissimilarity/similarity in orientation between matrices/subjects before functional alignment.

Based on the proof given in @Bakhtiar2015symmetrical, given that the input matrices are scaled (i.e. `rotational(scale=True)`), then the Procrustes distance is a true distance measure which obeys $0 < p(X, Y) < 1$ [@Bakhtiar2015symmetrical] (p. 322). Therefore we can convert the Procrustes distance to a similarity measure by subtracting it from 1.

# Results

## Step 1: Confirm the circular ordering of the circumplex scales

The results of the circular ordering test are shown in @tbl-circular-order. The following translations were not confirmed to have a circular ordering of their scales which matches the theoretical order: 'zsm' and 'vie'. They are therefore excluded from the following steps of the analysis.

{{< embed SuppMatB_CircE-Analysis.qmd#tbl-circular-order >}}


## Step 2: Confirm the quasi-circumplex structure of the circumplex scales

The results of the SEM model fit for the equal-communality quasi-circumplex structures are shown in @tbl-sem-res.

{{< embed SuppMatC_SSM-Analysis.ipynb#tbl-sem-res >}}

Of the remaining 16 languages considered, all but 4 pass the fit indices thresholds. The four which do not achieve the required performance are 'fra', 'kor', 'por', and 'jpn'. These are excluded from the following steps of the analysis.

## Step 3: Locate the full dataset circumplex scales within each language's circumplex space

As a demonstration of this process, @fig-profile-plots demonstrates the SSM process for locating each of the circumplex scales within the circumplex space of the 'cmn' translation. These profile plots show the correlation between the circumplex scales and the external variable (in this case, each of the general attributes) as a function of the angle of the circumplex scale. The SSM model fits a sinusoidal curve to the data points, and the parameters of this curve are used to determine the location of the circumplex scale within the circumplex space. These plots show clearly how adjusting the angles of the circumplex scales can improve the fit of the sinusoidal curve to the data points.

{{< embed SuppMatC_SSM-Analysis.ipynb#fig-profile-plots >}}

The model fit results for each translation are shown in @tbl-corr-angles-fit. Since every translation is able to adequately locate the circumplex scales, we can proceed to the final step of the analysis.

{{< embed SuppMatC_SSM-Analysis.ipynb#tbl-corr-angles-fit >}}

## Step 4: Accurately locating circumplex items within each language

@tbl-correspondence shows the results of the congruence test between the circumplex structure of the original instrument and the circumplex structure of the translated instruments. In addition to calculating these results with the adjusted angles to apply the Step 4 test, we also calculate the results using the unadjusted angles to demonstrate the impact of the adjustment.

{{< embed SuppMatC_SSM-Analysis.ipynb#tbl-correspondence >}}

When the adjusted angles for each translation are applied, the resulting circumplex scale location achieve good congruence with their theoretical locations. It should be noted that this is not the case without using the adjusted angles: locating the scales with the cmn translation using the unadjusted angles results in a score of 0.879, below the fit threshold of 0.9, but this increases to 0.990 when using the adjusted angles (see @fig-cmn-correspondence). All translations see some degree of improvement by using the adjusted angles.

@fig-cmn-correspondence gives an example of the impact of using the corrected angles for locating the circumplex scales.

{{< embed SuppMatC_SSM-Analysis.ipynb#fig-cmn-correspondence >}}

